Indeed Job Scraping and removing duplicate headers after parsing
jobsninja/ninjafun pull request #1
Opened 2023-01-30 03:52 UTC by jomanozgml

2023-01-30 07:33 UTC, kovarny requested changes

2023-01-30 07:33 UTC, kovarny commented on indeed_fetch.py
> +    description = await page.querySelector('div.jobsearch-JobComponent-description')
suggest we use tag names instead of classes to make it more generic

2023-01-30 07:33 UTC, kovarny commented on fetch_vacancy.py
> +        text = [title+'\n'] + [item.text+'\n' for item in list(tags)]
let's split this into separate function in a separate file

2023-01-30 07:33 UTC, kovarny commented on fetch_vacancy.py
> +        title, text = asyncio.get_event_loop().run_until_complete(fetch_vacancy_details())
can this be one separate function too?

2023-02-07 06:50 UTC, jomanozgml commented
# Description: Scrapes a URL and returns the HTML source from dynamic page using Scrape.do
# Free Plan comes with With 5 concurrent requests, a total of 1000 requests per month
# As application user scales up alternative required: Pyppeteer or Selenium or Node.js methods

2023-02-07 07:14 UTC, kovarny approved these changes

2023-02-07 07:14 UTC, kovarny commented on page_parser.py
> -
I suggest we still have the func definition comments

2023-02-07 07:14 UTC, merged